### ISSUE TITLE
Split Coordinator into Distribute and Collect

### ISSUE THREAD

**Issue by benzrf** [celluloid/ecell#2]
Should I split `Coordinator` into `Distribute` and `Collect`, or should I keep those two pieces of functionality in one Face? `Operative` has already been renamed to `Process`; if I did the split, `Distribute` would be the Face for pushing out tasks, and `Collect` would be the face for collecting processed results.

I'm asking primarily about the split, not about the specific names for the split pieces.

**Comment by digitalextremist** [comment]
Was about to comment on this with an answer, but I referenced to code to give an example or similar case -- but right now it is totally unrecognizable to me, so I will come back to this once you're more settled.

**Comment by digitalextremist** [comment]
@benzrf I will still weigh in more relevantly once I've seen the code at the pivot point between the migration of all code and the adapting it to a long-term state as we (both) begin to implement other ideas *using* the code.

For right now, I would say two things --

1) Even though the code is incomplete and still coming together -- all code you unextract, I will start migrating to to this `GitHub` repository in front of everyone so they can observe and chime in if they have even a small insight or thought. Everything that survives `unextracted/` will start to show up here soon.

2) On the actual thought here: `Distribution` with `Aggregate` and `Perform` or `Process`, followed by  made the most sense to me, but then it seems `Distribution` is already being used, in the code I now see? I would end with something like `Collate` vs. `Collect` because that also implies organizing it as well as being what @hintjens would call `Sink` in his book.

**Comment by digitalextremist** [comment]
I would vote `yes` do split into two faces on this shape, and worst case we mop up something later.

**Comment by benzrf** [comment]
Reopening this as an issue requesting that they actually get split.

**Comment by benzrf** [comment]
Wait, I already did that...
